import { useCallback, useEffect, useState } from 'react';
import { Check, Loader2, PencilLine, Sparkles, X } from 'lucide-react';
import { ticketsAPI } from '../../services/api';

const CONFIDENCE_STYLE = {
  high: 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-700 dark:text-emerald-200',
  medium: 'bg-amber-100 dark:bg-amber-500/20 text-amber-700 dark:text-amber-200',
  low: 'bg-red-100 dark:bg-red-500/20 text-red-600 dark:text-red-300',
};

/**
 * The draft→approve surface: an LLM-drafted reply staged by a workflow, shown
 * above the conversation for the agent to approve & send, copy into the
 * composer to edit, or dismiss. Sending goes through the normal reply path so
 * the thread, mirror and events behave exactly like a hand-written reply.
 */
export default function ProposedReplyCard({ ticketId, refreshToken = null, canWrite = false, onSent, onEditInComposer }) {
  const [proposal, setProposal] = useState(null);
  const [busy, setBusy] = useState(false);
  const [confirmDismiss, setConfirmDismiss] = useState(false);

  const load = useCallback(async () => {
    try {
      const res = await ticketsAPI.proposedReplies(ticketId);
      setProposal((res?.data || res || [])[0] || null);
    } catch { setProposal(null); }
  }, [ticketId]);

  useEffect(() => { load(); }, [load, refreshToken]);

  if (!proposal || !canWrite) return null;
  const confidence = String(proposal.confidence || '').toLowerCase();

  const send = async () => {
    if (busy) return;
    setBusy(true);
    try {
      await ticketsAPI.sendProposedReply(ticketId, proposal.id);
      setProposal(null);
      onSent?.();
    } catch { /* stale proposal — the refresh shows the true state */ }
    setBusy(false);
  };

  const dismiss = async () => {
    if (busy) return;
    setBusy(true);
    try {
      await ticketsAPI.dismissProposedReply(ticketId, proposal.id);
      setProposal(null);
    } catch { /* already decided */ }
    setBusy(false);
    setConfirmDismiss(false);
  };

  const editInComposer = async () => {
    onEditInComposer?.(proposal);
    // The draft moves to the composer — retire the proposal so it can't
    // double-send later.
    try { await ticketsAPI.dismissProposedReply(ticketId, proposal.id); } catch { /* fine */ }
    setProposal(null);
  };

  return (
    <div className="mb-4 rounded-xl border border-indigo-200 dark:border-indigo-500/30 bg-gradient-to-br from-indigo-50 dark:from-indigo-500/15 to-violet-50/60 dark:to-violet-500/10 p-3 animate-fadeIn" data-testid="proposed-reply-card">
      <div className="flex items-center gap-2 mb-2">
        <span className="h-6 w-6 rounded-full bg-indigo-600 text-white inline-flex items-center justify-center flex-shrink-0">
          <Sparkles className="w-3.5 h-3.5" aria-hidden="true" />
        </span>
        <p className="text-[11px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-300">
          {proposal.source === 'workflow_template' ? 'Workflow-drafted reply — awaiting your approval' : 'AI proposed reply — awaiting your approval'}
        </p>
        {confidence && (
          <span className={`ml-auto text-[10px] font-semibold uppercase px-1.5 py-0.5 rounded ${CONFIDENCE_STYLE[confidence] || 'bg-muted text-muted-foreground'}`}>
            {confidence} confidence
          </span>
        )}
      </div>
      <div className="rounded-lg bg-card/90 border border-indigo-100 dark:border-indigo-500/20 px-3.5 py-3 max-h-72 overflow-y-auto settings-scrollbar">
        {proposal.bodyHtml
          // Content is generated by our own guarded + sanitized LLM pipeline.
          ? <div className="prose prose-sm max-w-none text-foreground/85" dangerouslySetInnerHTML={{ __html: proposal.bodyHtml }} />
          : <p className="text-sm text-foreground/85 whitespace-pre-wrap">{proposal.bodyText}</p>}
      </div>
      <div className="mt-2.5 flex items-center gap-2">
        <button
          onClick={send}
          disabled={busy}
          className="tp-focus-ring inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600 text-white text-xs font-semibold hover:bg-indigo-700 disabled:opacity-60"
        >
          {busy ? <Loader2 className="w-3.5 h-3.5 animate-spin" aria-hidden="true" /> : <Check className="w-3.5 h-3.5" aria-hidden="true" />}
          Approve &amp; send
        </button>
        {onEditInComposer && (
          <button
            onClick={editInComposer}
            disabled={busy}
            className="tp-focus-ring inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-indigo-200 dark:border-indigo-500/30 text-indigo-700 dark:text-indigo-200 text-xs font-medium hover:bg-indigo-100/60 dark:hover:bg-indigo-500/15 disabled:opacity-60"
          >
            <PencilLine className="w-3.5 h-3.5" aria-hidden="true" /> Edit in composer
          </button>
        )}
        {confirmDismiss ? (
          <span className="ml-auto inline-flex items-center gap-1.5 text-xs">
            <span className="text-muted-foreground">Discard this draft?</span>
            <button onClick={dismiss} disabled={busy} className="tp-focus-ring px-2 py-1 rounded-md bg-red-600 text-white font-semibold hover:bg-red-700 disabled:opacity-60">Discard</button>
            <button onClick={() => setConfirmDismiss(false)} className="tp-focus-ring px-2 py-1 rounded-md text-muted-foreground hover:bg-muted">Keep</button>
          </span>
        ) : (
          <button
            onClick={() => setConfirmDismiss(true)}
            disabled={busy}
            aria-label="Dismiss proposed reply"
            className="tp-focus-ring ml-auto inline-flex items-center gap-1 px-2 py-1.5 rounded-lg text-xs text-muted-foreground/75 hover:text-red-600 dark:hover:text-red-300 hover:bg-red-50 dark:hover:bg-red-500/15"
          >
            <X className="w-3.5 h-3.5" aria-hidden="true" /> Dismiss
          </button>
        )}
      </div>
    </div>
  );
}
