version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ticketpulse-postgres
    environment:
      POSTGRES_DB: freshservice_dashboard
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d freshservice_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
