ALTER TABLE "tickets"
  ADD COLUMN "to_emails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "cc_emails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "reply_cc_emails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "fwd_emails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
